### ISSUE TITLE
data help

### ISSUE THREAD

**Issue by wlc9355** [ArtemSokolov/PanCanStem#1]
Hello, I have read the cell paper named 'Machine Learning Identifies Stemness Features Associated with Oncogenic Dedifferentiation', and known there was 'Stemness Index Workflow' in this website-http://tcgabiolinks.fmrp.usp.br/PanCanStem/ . However, I couldn't  Load this web page in my country. Could you please upload the 'Stemness Index Workflow'  in your github? Many thanks.

**Comment by ArtemSokolov** [comment]
Hi @wlc9355,

The workflow for generating mRNAsi can be found in `main.R` in this repository. I recommend running it as a Docker container, as described in the README. Please let me know if you run into problems with Docker.

Best,
-Artem

**Comment by wlc9355** [comment]
Thanks！ I'm trying it using the code you shared.
















At 2023-03-19 22:43:59, "Artem Sokolov" ***@***.***> wrote:

Hi @wlc9355,

The workflow for generating mRNAsi can be found in main.R in this repository. I recommend running it as a Docker container, as described in the README. Please let me know if you run into problems with Docker.

Best,
-Artem
