### ISSUE TITLE
main.R

### ISSUE THREAD

**Issue by minkichoi1103** [ArtemSokolov/PanCanStem#2]
Hello!

I'm not familiar with Docker, so I ran the script 'main.R' in RStudio. 
However, there are some problems with the code, specifically on lines 59 and 60. I think the function in that form doesn't work anymore because of the version of 'gelnet'.

Is it okay to just run 'gelnet(t(X.tr), NULL, 0, 1)'? 
If not, what is the correct code to get the mRNAsi?

Thank you!

**Comment by ArtemSokolov** [comment]
Hi @minkichoi1103,

Can you try installing the same version of the package as what's [in the container](https://github.com/ArtemSokolov/PanCanStem/blob/main/Dockerfile#L6)?
```
devtools::install_github("ArtemSokolov/gelnet")
```

**Comment by minkichoi1103** [comment]
Yes, I installed gelnet in that way.

Gelnet version 1.3.0 was installed, and then I ran the code on lines 59 and 60 of main.R. The result was as follows:

> mdef <- gelnet( t(X.tr) ) + model_oclr() + rglz_L2(1)
Error in gelnet(t(X.tr)) : argument "y" is missing, with no default

**Comment by ArtemSokolov** [comment]
Hm. It's calling the function at https://github.com/ArtemSokolov/gelnet/blob/master/R/def.R#L12, so there should be no `y`.

Can you do `args(gelnet::gelnet)` and make sure it shows the correct function signature?
```
> args(gelnet::gelnet)
function (X) 
NULL
```
If that's not the case, I would try removing and reinstalling the package.

I also ran the container for you and [added the output](https://github.com/ArtemSokolov/PanCanStem/tree/main/output) to the repository.

**Comment by minkichoi1103** [comment]
Thank you so much for all your answers.
Now it works! I also checked the output that you added to the repository.
Thanks!

**Comment by ArtemSokolov** [comment]
Excellent! Glad to hear you got it working.
